# Generated by Django 5.2.10 on 2026-06-04 06:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0061_revisablecluster_revisableclusterchild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streampage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('rich_text', 1), ('image', 2), ('product', 3), ('raw_html', 4), ('books', 5), ('title_list', 6), ('image_with_alt', 7), ('accordion', 10), ('comment', 11)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.test.testapp.models.ExtendedImageChooserBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('price', 0)]], {}), 4: ('wagtail.blocks.RawHTMLBlock', (), {}), 5: ('wagtail.blocks.StreamBlock', [[('title', 0), ('author', 0)]], {}), 6: ('wagtail.blocks.ListBlock', (0,), {}), 7: ('wagtail.images.blocks.ImageBlock', [], {}), 8: ('wagtail.blocks.StreamBlock', [[('accordion', 10), ('paragraph', 1)]], {}), 9: ('wagtail.blocks.LazyBlock', [8], {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('text', 0), ('replies', 13)]], {}), 12: ('wagtail.blocks.LazyBlock', [11], {}), 13: ('wagtail.blocks.ListBlock', (12,), {})}),
        ),
    ]
