# Generated by Django 5.2.10 on 2026-06-04 06:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamfield_migration_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='content',
            field=wagtail.fields.StreamField([('char1', 0), ('char2', 0), ('simplestruct', 1), ('simplestream', 2), ('simplelist', 3), ('nestedstruct', 4), ('nestedstream', 5), ('nestedlist_struct', 6), ('nestedlist_stream', 7), ('selfrefstruct', 8), ('mutualstruct', 13)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('char1', 0), ('char2', 0)]], {}), 2: ('wagtail.blocks.StreamBlock', [[('char1', 0), ('char2', 0)]], {}), 3: ('wagtail.blocks.ListBlock', (0,), {}), 4: ('wagtail.blocks.StructBlock', [[('char1', 0), ('stream1', 2), ('struct1', 1), ('list1', 3)]], {}), 5: ('wagtail.blocks.StreamBlock', [[('char1', 0), ('stream1', 2), ('struct1', 1), ('list1', 3)]], {}), 6: ('wagtail.blocks.ListBlock', (1,), {}), 7: ('wagtail.blocks.ListBlock', (2,), {}), 8: ('wagtail.blocks.StructBlock', [[('char1', 0), ('selfref', 10)]], {}), 9: ('wagtail.blocks.LazyBlock', [8], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StreamBlock', [[('struct1', 13), ('char1', 0)]], {}), 12: ('wagtail.blocks.LazyBlock', [11], {}), 13: ('wagtail.blocks.StructBlock', [[('char1', 0), ('stream1', 12)]], {})}),
        ),
        migrations.AlterField(
            model_name='samplepage',
            name='content',
            field=wagtail.fields.StreamField([('char1', 0), ('char2', 0), ('simplestruct', 1), ('simplestream', 2), ('simplelist', 3), ('nestedstruct', 4), ('nestedstream', 5), ('nestedlist_struct', 6), ('nestedlist_stream', 7), ('selfrefstruct', 8), ('mutualstruct', 13)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('char1', 0), ('char2', 0)]], {}), 2: ('wagtail.blocks.StreamBlock', [[('char1', 0), ('char2', 0)]], {}), 3: ('wagtail.blocks.ListBlock', (0,), {}), 4: ('wagtail.blocks.StructBlock', [[('char1', 0), ('stream1', 2), ('struct1', 1), ('list1', 3)]], {}), 5: ('wagtail.blocks.StreamBlock', [[('char1', 0), ('stream1', 2), ('struct1', 1), ('list1', 3)]], {}), 6: ('wagtail.blocks.ListBlock', (1,), {}), 7: ('wagtail.blocks.ListBlock', (2,), {}), 8: ('wagtail.blocks.StructBlock', [[('char1', 0), ('selfref', 10)]], {}), 9: ('wagtail.blocks.LazyBlock', [8], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StreamBlock', [[('struct1', 13), ('char1', 0)]], {}), 12: ('wagtail.blocks.LazyBlock', [11], {}), 13: ('wagtail.blocks.StructBlock', [[('char1', 0), ('stream1', 12)]], {})}),
        ),
    ]
